#!/bin/bash

if [ ${UID} -ne 0] then,
  echo "you need root access"
  echo
 exit 1
 fi
##check numbers of processors

if [ nproc -eq 1 ]
then
	echo " This server is too small"
	exit2
fi

echo " this is a github repository"
